# Generated by Django 2.2.1 on 2019-05-16 01:57

from django.db import migrations, models
import django.db.models.deletion
import movie.models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='star',
            field=movie.models.IntegerRangeField(verbose_name=range(1, 10)),
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor1', models.CharField(max_length=30)),
                ('actor2', models.CharField(max_length=30)),
                ('actor3', models.CharField(max_length=30)),
                ('actor4', models.CharField(max_length=30)),
                ('actor5', models.CharField(max_length=30)),
                ('actor6', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=30)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie')),
            ],
        ),
    ]
